-- 0012_event_evidence_suggestions.sql
-- Project Daylight - AI-suggested evidence infrastructure
--
-- This migration adds a table for storing AI-generated evidence suggestions
-- that are tied to specific timeline events. Suggestions are generated by
-- backend LLM routes and can later be surfaced in the UI so users can decide
-- which evidence to gather or upload.
--
-- Run this in your Supabase project's SQL editor.
--
-- Dependencies:
-- - 0001_initial_schema.sql (for events, evidence_source_type, evidence_mention_status, audit helpers)
-- - 0010_cases_schema.sql (optional contextual data for prompts, not required for the table itself)

------------------------------------------------------------
-- Event evidence suggestions
------------------------------------------------------------

-- Reuse existing enums from 0001_initial_schema.sql:
--   evidence_source_type:  'text' | 'email' | 'photo' | 'document' | 'recording' | 'other'
--   evidence_mention_status: 'have' | 'need_to_get' | 'need_to_create'

create table if not exists public.event_evidence_suggestions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  event_id uuid not null references public.events (id) on delete cascade,

  -- What kind of evidence is being suggested (aligned with evidence.source_type)
  evidence_type evidence_source_type not null,

  -- Whether this is something the user already has, needs to obtain, or needs to create
  evidence_status evidence_mention_status not null,

  -- Human-readable description of the suggested evidence
  description text not null,

  -- Optional link to a concrete evidence item once the user fulfills this suggestion
  fulfilled_evidence_id uuid references public.evidence (id) on delete set null,
  fulfilled_at timestamptz,

  -- When the user decides a suggestion is not helpful/relevant
  dismissed_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_event_evidence_suggestions_user_event
  on public.event_evidence_suggestions (user_id, event_id, created_at desc);

alter table public.event_evidence_suggestions enable row level security;

create policy "Users can manage own event evidence suggestions"
  on public.event_evidence_suggestions
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

------------------------------------------------------------
-- Triggers for updated_at and audit logging
------------------------------------------------------------

create trigger event_evidence_suggestions_set_updated_at
before update on public.event_evidence_suggestions
for each row
execute function public.set_updated_at();

create trigger audit_event_evidence_suggestions
after insert or update or delete on public.event_evidence_suggestions
for each row
execute function public.record_audit();



